### ISSUE TITLE
Add the color variations

### ISSUE THREAD

**Issue by brxoo** [armanelgtron/Kvantum-Mint-Y#1]
First, thank you for the theme you made. This was the only Mint-Y theme for kvantum I found. But I would like you to create one with the new Linux Mint colors, especially the new Linux Mint main theme (https://github.com/linuxmint/mint-themes/tree/master/files/usr/share/themes/Mint-Y-Dark-Aqua) this theme would fit perfectly in new versions of Mint.

**Comment by armanelgtron** [comment]
Done.
