### ISSUE TITLE
Color variation highlight color not correct

### ISSUE THREAD

**Issue by esa1975** [armanelgtron/Kvantum-Mint-Y#2]
Hello. Thank you for taking the time to put this together. I really appreciate it. I am trying to use the Dark Blue variant and I am seeing the wrong color for highlights. I am using VirtualBox. Here's what it looks like.

![Kvantum Mint Y Dark Blue Theme](https://user-images.githubusercontent.com/50505461/230659830-8ec0e81d-c38e-4bdf-b41c-a7c4e5f7bd0f.png)

Here's the theme selected in Kvantum.

![Kvantum Theme](https://user-images.githubusercontent.com/50505461/230659995-a1dc41c4-9387-4be8-a166-15ca638956d4.png)

I performed some additional testing and found that the non-dark color variants are working as expected but none of the dark variants seem to be.

I'm running Cinnamon (cinnamon-desktop 5.6.1-1) on EndeavourOS. Let me know if you'd like me to test anything or if you need additional info. Thanks!

**Comment by armanelgtron** [comment]
I've updated the color variation script to take into account several different shades of the selection color used, so this should be fixed now.

**Comment by esa1975** [comment]
Thank you for the quick response. I can confirm that it is working as intended.
